# Dockerfile.gateway
FROM nginx:alpine

# Necesitamos envsubst
RUN apk add --no-cache gettext

# Copiamos plantilla y entrypoint
COPY nginx.conf.template /etc/nginx/nginx.conf.template
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
